# -*- coding: utf-8 -*-
{
    'name': 'Vahini Dashboard',
    'author': 'Prixgen Tech Solutions Pvt. Ltd.',
    'website': 'https://www.prixgen.com',
    'company': 'Prixgen Tech Solutions Pvt. Ltd.',
    'category': 'Uncategorized',
    'App origin': 'base',
    'version': '18.0.0.111',
    'license': 'LGPL-3',
    'depends': ['web', 'account', 'sale'],
    'data': [
        'security/ir.model.access.csv',
        'views/vahini_dashboard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # ── SCSS ──────────────────────────────────────────────
            'vahini_dashboard/static/src/scss/variables.scss',
            'vahini_dashboard/static/src/scss/announcements.scss',
            'vahini_dashboard/static/src/scss/layout.scss',
            'vahini_dashboard/static/src/scss/sidebar.scss',
            'vahini_dashboard/static/src/scss/header.scss',
            'vahini_dashboard/static/src/scss/toolbar.scss',
            'vahini_dashboard/static/src/scss/metrics.scss',
            'vahini_dashboard/static/src/scss/charts.scss',
            'vahini_dashboard/static/src/scss/tables.scss',
            'vahini_dashboard/static/src/scss/modal.scss',
            'vahini_dashboard/static/src/scss/pagination.scss',
            'vahini_dashboard/static/src/scss/loading.scss',
            'vahini_dashboard/static/src/scss/dayview.scss',
            'vahini_dashboard/static/src/scss/mapview.scss',
            'vahini_dashboard/static/src/scss/paymentview.scss',
            'vahini_dashboard/static/src/scss/followupview.scss',
            'vahini_dashboard/static/src/scss/itemview.scss',
            'vahini_dashboard/static/src/scss/gpview.scss',
            'vahini_dashboard/static/src/scss/trendview.scss',
            'vahini_dashboard/static/src/scss/itemmaster.scss',
            # ── JS ────────────────────────────────────────────────
            'vahini_dashboard/static/src/js/chart_loader.js',
            'vahini_dashboard/static/src/js/icons.js',
            'vahini_dashboard/static/src/js/utils.js',
            'vahini_dashboard/static/src/js/dashboardData.js',
            # ── OWL Components JS ─────────────────────────────────
            'vahini_dashboard/static/src/components/SideDrawer/SideDrawer.js',
            'vahini_dashboard/static/src/components/SnapHeader/SnapHeader.js',
            'vahini_dashboard/static/src/components/SnapMetrics/SnapMetrics.js',
            'vahini_dashboard/static/src/components/ChartCard/ChartCard.js',
            'vahini_dashboard/static/src/components/DataTable/DataTable.js',
            'vahini_dashboard/static/src/components/CompareModal/CompareModal.js',
            'vahini_dashboard/static/src/components/DayView/DayView.js',
            'vahini_dashboard/static/src/components/PurchaseView/PurchaseView.js',
            'vahini_dashboard/static/src/components/MapView/MapView.js',
            'vahini_dashboard/static/src/components/PaymentView/PaymentView.js',
            'vahini_dashboard/static/src/components/FollowUpView/FollowUpView.js',
            'vahini_dashboard/static/src/components/ItemView/ItemView.js',
            'vahini_dashboard/static/src/components/GpView/GpView.js',
            'vahini_dashboard/static/src/components/TrendView/TrendView.js',
            'vahini_dashboard/static/src/components/ItemMaster/ItemMaster.js',
            'vahini_dashboard/static/src/components/InvoiceView/InvoiceView.js',
            'vahini_dashboard/static/src/components/AnnouncementPanel/AnnouncementPanel.js',
            # ── Root component ────────────────────────────────────
            'vahini_dashboard/static/src/js/VahiniDashboard.js',
            # ── XML (icon.xml must be first) ──────────────────────
            'vahini_dashboard/static/src/xml/icon.xml',
            'vahini_dashboard/static/src/components/SideDrawer/SideDrawer.xml',
            'vahini_dashboard/static/src/components/SnapHeader/SnapHeader.xml',
            'vahini_dashboard/static/src/components/SnapMetrics/SnapMetrics.xml',
            'vahini_dashboard/static/src/components/ChartCard/ChartCard.xml',
            'vahini_dashboard/static/src/components/DataTable/DataTable.xml',
            'vahini_dashboard/static/src/components/CompareModal/CompareModal.xml',
            'vahini_dashboard/static/src/components/DayView/DayView.xml',
            'vahini_dashboard/static/src/components/PurchaseView/PurchaseView.xml',
            'vahini_dashboard/static/src/components/MapView/MapView.xml',
            'vahini_dashboard/static/src/components/PaymentView/PaymentView.xml',
            'vahini_dashboard/static/src/components/FollowUpView/FollowUpView.xml',
            'vahini_dashboard/static/src/components/ItemView/ItemView.xml',
            'vahini_dashboard/static/src/components/GpView/GpView.xml',
            'vahini_dashboard/static/src/components/TrendView/TrendView.xml',
            'vahini_dashboard/static/src/components/ItemMaster/ItemMaster.xml',
            'vahini_dashboard/static/src/components/InvoiceView/InvoiceView.xml',
            'vahini_dashboard/static/src/components/AnnouncementPanel/AnnouncementPanel.xml',
            'vahini_dashboard/static/src/xml/VahiniDashboard.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
